export declare class SpacetimeApp {
    private readonly container;
    private readonly hud;
    private renderer;
    private scene;
    private camera;
    private controls;
    private world;
    private watchUI;
    private controllers;
    private interactables;
    private raycaster;
    private tmpMatrix;
    private tmpDir;
    private tmpOrigin;
    private tmpCameraPos;
    private tmpPos;
    private clock;
    private debugPanel;
    private messagePanel;
    private twoHand;
    constructor(container: HTMLElement, hud: HTMLElement);
    start(): void;
    private setupInitialScene;
    private setupControllers;
    private attachWatchToGrip;
    private onSelectStart;
    private onSelectEnd;
    private onSqueezeStart;
    private onSqueezeEnd;
    private tryBeginTwoHand;
    private updateTwoHandTransform;
    private isBothSqueezing;
    private handleSelection;
    private handleWatchAction;
    private findFirstIntersection;
    private updateControllerHover;
    private updateLaser;
    private render;
    private syncWatchUI;
    private refreshInteractables;
    private updateHud;
    private isTriggerPressed;
    private updateHudText;
    private onResize;
    private getViewerPosition;
    private getHand;
    private createMessagePanel;
    private createDebugPanel;
    private updateDebugPanel;
}
